version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11.5

    # working_directory: /app

    steps:
      - checkout

      - run:
          name: Initialize venv / Install dependencies
          command: |
            # Créer un environnement virtuel
            python -m venv venv
            
            # Activer l'environnement virtuel sur Windows
            .\venv\Scripts\activate
            
            # Installer les dépendances à partir de requirements.txt
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
