version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11.5

    # working_directory: /app
    steps:
      - checkout

      - run:
          name: Initialize venv
          command:
            python -m venv venv
           .\venv\Scripts\activate
        
      - run:
          name: Install dependencies
          command:
            pip install -r requirements.txt

      - run:
          name: Linting
          command: flake8

      - run:
          name: Run tests
          command: pytest

  Containerize:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t python-oc-lettings-fr-server .
            docker tag P13_Docker_Image:latest samichelly/python-oc-lettings-fr-server:latest
            docker push samichelly/python-oc-lettings-fr-server:latest

            # samichelly/python-oc-lettings-fr-server:tagname


  Deployment:
        docker:
        - image: cimg/base:stable
        steps:
        - checkout
        - run:
            name: "Deploy"
            command: curl -X GET https://api.render.com/deploy/srv-cn2lrr821fec73e4ado0?key=yl8O7hCN0dA

workflows:
  version: 2
  build:
    jobs:
      - build
      # - containerize:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - deploy:
      #     requires:
      #       - build
      #       - containerize
      #     filters:
      #       branches:
      #         only:
      #           - master

    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master



