# Generated by Django 3.0 on 2024-01-29 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oc_lettings_site", "0002_auto_20240129_1834"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                )
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Profile",
                    table="profiles_profile",
                ),
            ],
        ),
    ]
